version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
      - ./.env:/usr/app/.env  # Mount .env
    ports:
      - "8080:8080"
    env_file:
      - ./.env  # Load environment variables for the server

  couchdb:
    image: couchdb:3
    ports:
      - "5984:5984"
    volumes:
      - ./couchdb/config:/opt/couchdb/etc/local.d  # Mount local.ini config
      - ./couchdb/data:/opt/couchdb/data  # Persist data to local filesystem
    environment:
      COUCHDB_USER: ${COUCHDB_ADMIN_USER}  # Use environment variable from .env
      COUCHDB_PASSWORD: ${COUCHDB_ADMIN_PASSWORD}  # Use environment variable from .env
      COUCHDB_SECRET: ${COUCHDB_SECRET}
    env_file:
      - ./.env  # Load environment variables for CouchDB

volumes:
  couchdb_data:  # Define the volume for CouchDB data
