version: '3'

services:
  server:
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
    command: sh -c "npm run ${NODE_ENV:-prod}"  # Use NODE_ENV to control the mode
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
      - ./.env:/usr/app/.env  # Mount .env
    ports:
      - "8080:8080"
    env_file:
      - ./.env  # Load environment variables for the server
    environment:
      - NODE_ENV=${NODE_ENV:-prod}  # Default to 'prod' if NODE_ENV is not set

  couchdb:
    restart: unless-stopped
    build: ./couchdb # Use Dockerfile
    ports:
      - "5984:5984"
    volumes:
      - ./couchdb/data:/opt/couchdb/data  # Persist data to local filesystem
    environment:
      COUCHDB_USER: ${COUCHDB_ADMIN_USER}  # Use environment variable from .env
      COUCHDB_PASSWORD: ${COUCHDB_ADMIN_PASSWORD}  # Use environment variable from .env
    env_file:
      - ./.env  # Load environment variables for CouchDB

volumes:
  couchdb_data:  # Define the volume for CouchDB data
