services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./server:/usr/app
      - /usr/app/node_modules
    ports:
      - "8080:8080"